### ISSUE TITLE
python-dotenv instructions.

### ISSUE THREAD

**Issue by code-monk08** [code-monk08/opentrivia#21]
We can add python-dotenv instructions to the README.md.

**Comment by ppmadalin** [comment]
Well, there are not to much things to say:

In order to use python-dev with flask you need to install it first:
`pip install python-dotenv`

Then you can just write the environment variable name and value in a `.flaskenv` file in the top-level directory of the project:
```
# eg of .flaskenv content
FLASK_APP=mayapp.py
```

`.flaskenv` file is loaded automatically if python-dotenv is installed in your virtualenv.

Also usually you will add another file called `.env`. In this file you should keep the sensitive variables, like secret key. In `.flaskenv` file you should keep the public variables and should be versioned too. Both will be loaded automatically by flask. 

If you want to load these files manually you can do the following:

```
# settings.py
import os
from os.path import join, dirname
from dotenv import load_dotenv

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

SECRET_KEY = os.environ.get("SECRET_KEY")
DATABASE_PASSWORD = os.environ.get("DATABASE_PASSWORD")
```
